name: Visual regression testing using Applitools

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_TOKEN }}
  APPLITOOLS_BATCH_ID: ${{ github.sha }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Log Git SHA
        run: echo "$GITHUB_SHA"
      - name: View files
        run: tree -h -L 1
      - name: Install dependencies
        run: npm i
      - name: Build Storybook
        run: npm run build-storybook
      - name: Visual regression testing using Applitools
        run: npx eyes-storybook