name: Visual regression testing using Applitools

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_TOKEN }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Waiting for Netlify preview
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: waitForNetlify
        with:
          site_name: "gifted-tesla-96fe2e"
      - name: Visual regression testing using Applitools
        run: npx @applitools/eyes-storybook -u ${{ steps.waitForNetlify.outputs.url }}
