name: Visual regression testing using Applitools

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_TOKEN }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Visual regression testing using Applitools
        run: npx @applitools/eyes-storybook -u https://deploy-preview-${{ github.event.pull_request.number }}--gifted-tesla-96fe2e.netlify.app/
