name: Visual regression testing using Applitools

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_TOKEN }}
  APPLITOOLS_BATCH_ID: ${{ github.sha }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Log Git SHA
        run: echo "$GITHUB_SHA"
      - name: Build Storybook
        run: |
          yarn
          yarn build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3yarn
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
      - name: Visual regression testing using Applitools
        run: npx eyes-storybook
  batch-completion-notification:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status 
        uses: wei/curl@v1.1.1
        with:
          args: -d "" -X POST https://eyesapi.applitools.com/api/externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/complete?apiKey=${{ secrets.APPLITOOLS_API_KEY }}
