name: UMD checker

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check UMD size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          exclude: "{./dist/*.report.html,**/*.map,**/node_modules/**}"
      - name: Check UMD
        run: |
          rm -rf test-that-umd-for-god-sake.js
          cat <<EOT >> test-that-umd-for-god-sake.js
          Object.values(require(`./dist/TalendDesignSystem.min.js.dependencies.json`)).forEach(
          	function requireDependency(dependency) {
          		global[dependency.var] = require(dependency.name);
          	},
          );
          global[UMDName] = require(`./dist/TalendDesignSystem.min.js`);
          const UMDContent = Object.keys(global[UMDName]);
          if (UMDContent.length > 0) {
          	console.log(UMDContent);
          	process.exit(0);
          }
          process.exit(1);
          EOT
          node ./test-that-umd-for-god-sake.js
        env:
          UMD_NAME: TalendDesignSystem
